name: KMP Test And Build All Targets

on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    branches:
      - main
      - release/**

jobs:
  test-on-pr:
    name: Run KMP Tests
    uses: ./.github/workflows/kmp-reusable-test-all-targets.yml
    secrets: inherit

  build-on-pr:
    name: Build All KMP Targets
    uses: ./.github/workflows/kmp-reusable-build-all-targets.yml
    secrets: inherit